[http.middlewares.simpleAuth.basicAuth]
  users = [
    "esteban:$apr1$f23eLsMF$diRxN2ygDkQV2ocerNCDY"
  ]
  [http.routers.api]
    rule = "Host(`monitor.estebanpro.online`)"
    entrypoints = ["websecure"]
    middlewares = "simpleAuth"
    service = "api@internal"
    [http.routers.api.tls]
      certResolver = "lets-encrypt"
